import { servicePhotos } from '../assets/images.js'

/**
 * Single source of truth for the six core services. Used by the services list
 * page (/services) and each dedicated detail page (/services/<id>).
 */
export const SERVICES = [
  {
    id: 'standard',
    photo: servicePhotos.standard,
    no: '01',
    badge: 'Most popular',
    title: 'Standard Cleaning',
    tagline: 'A fresh, effortless home — every single week.',
    blurb: 'Reliable upkeep that keeps a clean, comfortable home fresh from room to room.',
    price: 'From $120',
    duration: '2–3 hours',
    includes: [
      'Dusting of all reachable surfaces',
      'Wiping counters, sinks & fixtures',
      'Bathrooms: showers, tubs, toilets & mirrors',
      'Vacuum & mop every floor',
      'Empty bins & tidy common areas',
    ],
    rooms: [
      ['Kitchen', 'Counters, sink, stovetop and appliance exteriors wiped; floor mopped.'],
      ['Bathrooms', 'Showers, tubs, toilets and mirrors scrubbed and shined.'],
      ['Living areas', 'Surfaces dusted, floors vacuumed, cushions tidied.'],
      ['Bedrooms', 'Dusted, floors cleaned and beds made on request.'],
    ],
    idealFor: 'Busy households wanting consistent upkeep.',
  },
  {
    id: 'deep',
    photo: servicePhotos.deep,
    no: '02',
    badge: 'Best value',
    title: 'Deep Cleaning',
    tagline: 'The top-to-bottom reset your home has been craving.',
    blurb: 'For homes that need extra attention — the detailed areas a standard clean skips.',
    price: 'From $220',
    duration: '4–6 hours',
    includes: [
      'Everything in a standard clean, taken further',
      'Baseboards, door frames & light switches',
      'Inside appliances, tile & grout',
      'High-touch surfaces sanitised',
      'Behind and under movable furniture',
    ],
    rooms: [
      ['Detail work', 'Baseboards, trim, door frames and switch plates by hand.'],
      ['Kitchen deep', 'Inside the oven and fridge on request; grout and tile revived.'],
      ['Bathroom deep', 'Grout, glass, vents and fixtures descaled and polished.'],
      ['Hidden spots', 'Behind and under movable furniture and appliances.'],
    ],
    idealFor: 'First-time cleans, spring resets or overdue scrubs.',
  },
  {
    id: 'move',
    photo: servicePhotos.move,
    no: '03',
    badge: 'Turnkey',
    title: 'Move-In / Move-Out',
    tagline: 'Walk away with your deposit — or into a spotless start.',
    blurb: 'Take the stress out of relocating with an empty-home clean that passes inspection.',
    price: 'From $260',
    duration: '4–7 hours',
    includes: [
      'Full interior deep clean, top to bottom',
      'Kitchens, bathrooms & appliances',
      'Inside cabinets, drawers & closets',
      'Wall spot-cleaning & baseboards',
      'Move-out checklist for deposit returns',
    ],
    rooms: [
      ['Whole interior', 'Every room deep-cleaned as if no one has ever lived there.'],
      ['Inside everything', 'Cabinets, drawers, closets, oven, fridge and dishwasher.'],
      ['Walls & trim', 'Spot-cleaned walls, baseboards and door frames.'],
      ['Inspection-ready', 'Finished against a landlord/turnover checklist.'],
    ],
    idealFor: 'Tenants, landlords and anyone turning over a property.',
  },
  {
    id: 'post',
    photo: servicePhotos.post,
    no: '04',
    badge: 'Specialty',
    title: 'Post-Construction',
    tagline: 'From dusty job site to move-in day, made brilliant.',
    blurb: 'Newly built or renovated spaces made ready to live in — dust, debris and grime gone.',
    price: 'From $320',
    duration: '5–8 hours',
    includes: [
      'Fine construction dust removal',
      'Paint, adhesive & sticker cleanup',
      'Detailed wipe-down of every surface',
      'Windows, tracks & fixtures',
      'Debris haul-away coordination',
    ],
    rooms: [
      ['Dust removal', 'Fine construction dust cleared from every surface and vent.'],
      ['Residue cleanup', 'Paint specks, adhesive, stickers and labels removed.'],
      ['Glass & tracks', 'Windows, sills and tracks detailed inside and out.'],
      ['Final polish', 'Fixtures wiped, floors finished, debris hauled away.'],
    ],
    idealFor: 'Renovations, new builds and remodels.',
  },
  {
    id: 'office',
    photo: servicePhotos.office,
    no: '05',
    badge: 'For business',
    title: 'Commercial Cleaning',
    tagline: 'A workplace that impresses — cleaned around your hours.',
    blurb: 'Offices, retail spaces and businesses cleaned on a schedule that never disrupts your team.',
    price: 'Custom quote',
    duration: 'Flexible',
    includes: [
      'Workstations, desks & shared surfaces',
      'Lobbies, kitchens & break rooms',
      'Restrooms sanitised & restocked',
      'Trash & recycling handled',
      'Flexible after-hours scheduling',
    ],
    rooms: [
      ['Workspaces', 'Desks, workstations and shared surfaces wiped and sanitised.'],
      ['Common areas', 'Lobbies, break rooms and kitchens kept guest-ready.'],
      ['Restrooms', 'Sanitised, restocked and checked on a schedule.'],
      ['After hours', 'Cleaned before or after your team is in the building.'],
    ],
    idealFor: 'Offices, clinics, studios and retail spaces.',
  },
  {
    id: 'recurring',
    photo: servicePhotos.recurring,
    no: '06',
    badge: 'Save more',
    title: 'Recurring Cleaning',
    tagline: 'Never think about cleaning again. Ever.',
    blurb: 'Keep your home effortlessly fresh on a weekly, bi-weekly or monthly schedule.',
    price: 'From $99',
    duration: 'Per visit',
    includes: [
      'Weekly, bi-weekly or monthly visits',
      'The same trusted crew each time',
      'Lower per-visit rates than one-offs',
      'Easy reschedule, skip or cancel',
      'Priority same-week booking',
    ],
    rooms: [
      ['Your rhythm', 'Weekly, bi-weekly or monthly — whatever fits your life.'],
      ['Same crew', 'The same trusted, background-checked cleaners each visit.'],
      ['Best rates', 'Lower per-visit pricing than one-off cleans.'],
      ['Total control', 'Reschedule, skip or cancel any visit in seconds.'],
    ],
    idealFor: 'Anyone who never wants to think about cleaning again.',
  },
]

export function findService(id) {
  return SERVICES.find((s) => s.id === id) ?? null
}
